apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    name: busybox-test
spec:
  restartPolicy: Always
  containers:
    - image: busybox
      name: busybox
      volumeMounts:
      - mountPath: "/data"
        name: vol
      command: [ "sleep", "1000000" ]
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: storage-pvc
